FROM golang:alpine as builder

RUN apk add --no-cache git

RUN go get github.com/golang/dep/cmd/dep
RUN go get github.com/codegangsta/gin

WORKDIR /go/src/github.com/gpsamson/segment-redis-proxy

ADD Gopkg.toml Gopkg.toml
ADD Gopkg.lock Gopkg.lock

RUN dep ensure --vendor-only

ADD . .

EXPOSE 8080
