version: '3.3'

volumes:
  redis_data:

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: gin -i -a 8080 run main.go
    image: gpsamson/segment-redis-proxy
    volumes:
      - .:/go/src/github.com/gpsamson/segment-redis-proxy
    environment:
      - PORT=8080
      - PROTOCOL=RESP
      - REDIS_ADDR=redis:6379
      - CACHE_CAPACITY=100
      - CACHE_TTL=300
    ports:
      - '8080:8080'
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    expose:
      - 6379
    ports:
      - '6379:6379'
